# Generated by Django 4.1.7 on 2023-04-01 06:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bmenu',
            fields=[
                ('BmenuID', models.AutoField(primary_key=True, serialize=False)),
                ('BmenuName', models.CharField(max_length=20)),
                ('Bmenuclass', models.IntegerField(default='')),
                ('BmenuPrice', models.IntegerField(default='')),
                ('BmenuState', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='breakfast',
            fields=[
                ('breakfastID', models.AutoField(primary_key=True, serialize=False)),
                ('breakfastNum', models.IntegerField(default='1')),
                ('breakfastPrice', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('DinnerID', models.AutoField(primary_key=True, serialize=False)),
                ('DinnerNum', models.IntegerField(default='1')),
                ('DinnerPrice', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Dmenu',
            fields=[
                ('DmenuID', models.AutoField(primary_key=True, serialize=False)),
                ('DmenuName', models.CharField(max_length=20)),
                ('Dmenuclass', models.IntegerField(default='')),
                ('DmenuPrice', models.IntegerField(default='')),
                ('DmenuState', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('JoinID', models.AutoField(primary_key=True, serialize=False)),
                ('JoinName', models.CharField(max_length=10)),
                ('JoinCard', models.CharField(max_length=10)),
                ('JoinInsurance', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('memberID', models.AutoField(primary_key=True, serialize=False)),
                ('memberclass', models.CharField(max_length=4)),
                ('memberLine', models.CharField(max_length=20)),
                ('memberFB', models.CharField(max_length=20)),
                ('memberName', models.CharField(max_length=20)),
                ('memberTel', models.IntegerField(default='')),
                ('memberEmail', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator])),
            ],
        ),
        migrations.CreateModel(
            name='travel',
            fields=[
                ('travelID', models.AutoField(primary_key=True, serialize=False)),
                ('travelDate', models.CharField(max_length=10)),
                ('travelState', models.IntegerField(default='')),
                ('travelPrice', models.IntegerField(default='15000元')),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.member')),
            ],
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(check=models.Q(('memberLine__isnull', False), ('memberFB__isnull', False), _connector='OR'), name='memberLine_or_memberFB'),
        ),
        migrations.AlterUniqueTogether(
            name='dmenu',
            unique_together={('DmenuID', 'DmenuName')},
        ),
        migrations.AddField(
            model_name='dinner',
            name='DinnerOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dmenu'),
        ),
        migrations.AddField(
            model_name='dinner',
            name='Dinnertravel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.travel'),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='breakfastOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bmenu'),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='breakfasttravel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.travel'),
        ),
        migrations.AlterUniqueTogether(
            name='bmenu',
            unique_together={('BmenuID', 'BmenuName')},
        ),
    ]
